 // Cek URL saat ini dan sesuaikan dengan kondisi yang diinginkan
     const urlMapping = {
    "https://www.betonjayareadymix.com/2021/08/jayamix-pangandaran.html": "Jayamix Pangandaran",
    "https://www.betonjayareadymix.com/2021/08/jayamix-sumedang.html": "Jayamix Sumedang",
    "https://www.betonjayareadymix.com/2021/08/jayamix-sukabumi.html": "Jayamix Sukabumi",
    "https://www.betonjayareadymix.com/2021/08/jayamix-karawang.html": "Jayamix Karawang",
    "https://www.betonjayareadymix.com/2021/08/jayamix-kuningan.html": "Jayamix Kuningan",
    "https://www.betonjayareadymix.com/2021/08/jayamix-tasikmalaya.html": "Jayamix Tasikmalaya",
    "https://www.betonjayareadymix.com/2021/08/jayamix-subang.html": "Jayamix Subang",
    "https://www.betonjayareadymix.com/2021/08/jayamix-blitar.html": "Jayamix Blitar",
    "https://www.betonjayareadymix.com/2021/08/jayamix-klaten.html": "Jayamix Klaten",
    "https://www.betonjayareadymix.com/2021/08/jayamix-jakarta.html": "Jayamix Jakarta",
    "https://www.betonjayareadymix.com/2018/04/scg-jayamix.html": "SCG Jayamix",
    "https://www.betonjayareadymix.com/2021/08/jayamix-purwakarta.html": "Jayamix Purwakarta",
    "https://www.betonjayareadymix.com/2021/03/perbedaan-jayamix-dan-readymix.html": "Perbedaan Jayamix dan Ready Mix",
    "https://www.betonjayareadymix.com/2021/03/ukuran-jayamix.html": "Ukuran Jayamix",
    "https://www.betonjayareadymix.com/2021/03/1-mobil-jayamix-berapa-kubik.html": "1 Mobil Jayamix berapa kubik",
    "https://www.betonjayareadymix.com/2021/03/cara-pesan-jayamix.html": "Cara Pesan Jayamix",
    "https://www.betonjayareadymix.com/2021/03/jayamix-terdekat.html": "Jayamix Terdekat",
    "https://www.betonjayareadymix.com/2021/03/jayamix-beton.html": "Jayamix Beton",
    "https://www.betonjayareadymix.com/2021/03/jayamix-bogor.html": "Jayamix Bogor",
    "https://www.betonjayareadymix.com/2021/03/jayamix-bekasi.html": "Jayamix Bekasi",
    "https://www.betonjayareadymix.com/2021/03/jayamix-cikarang.html": "Jayamix Cikarang",
    "https://www.betonjayareadymix.com/2021/03/jayamix-depok.html": "Jayamix Depok",
    "https://www.betonjayareadymix.com/2021/03/jayamix-cibubur.html": "Jayamix Cibubur",
    "https://www.betonjayareadymix.com/2021/03/jayamix-bandung.html": "Jayamix Bandung",
    "https://www.betonjayareadymix.com/2021/03/jayamix-cirebon.html": "Jayamix Cirebon",
    "https://www.betonjayareadymix.com/2021/03/jayamix-cianjur.html": "Jayamix Cianjur",
    "https://www.betonjayareadymix.com/2021/03/jayamix-cikande.html": "Jayamix Cikande",
    "https://www.betonjayareadymix.com/2021/03/jayamix-cilegon.html": "Jayamix Cilegon",
    "https://www.betonjayareadymix.com/2021/03/jayamix-ciamis.html": "Jayamix Ciamis",
    "https://www.betonjayareadymix.com/2021/03/jayamix-garut.html": "Jayamix Garut",
     "https://www.betonjayareadymix.com/2021/03/holcim-ready-mix.html": "Holcim Ready Mix",
    "https://www.betonjayareadymix.com/2021/03/ready-mix-terdekat.html": "Ready Mix Terdekat",
    "https://www.betonjayareadymix.com/2021/03/ready-mix-karawang.html": "Ready Mix Karawang",
    "https://www.betonjayareadymix.com/2021/03/ready-mix-sukabumi.html": "Ready Mix Sukabumi",
    "https://www.betonjayareadymix.com/2021/03/ready-mix-purwakarta.html": "Ready Mix Purwakarta",
    "https://www.betonjayareadymix.com/2021/09/harga-jayamix-pati.html": "Harga Jayamix Pati",
    "https://www.betonjayareadymix.com/2021/09/harga-jayamix-klaten.html": "Harga Jayamix Klaten",
    "https://www.betonjayareadymix.com/2021/09/harga-jayamix-gresik.html": "Harga Jayamix Gresik",
    "https://www.betonjayareadymix.com/2021/09/harga-jayamix-sidoarjo.html": "Harga Jayamix Sidoarjo",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-jombang.html": "Harga Jayamix Jombang",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-jawa-timur.html": "Harga Jayamix Jawa Timur",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-tangerang.html": "Harga Jayamix Tangerang",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-bogor.html": "Harga Jayamix Bogor",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-garut.html": "Harga Jayamix Garut",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-bandung.html": "Harga Jayamix Bandung",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-bekasi.html": "Harga Jayamix Bekasi",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-cikarang.html": "Harga Jayamix Cikarang",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-cibinong.html": "Harga Jayamix Cibinong",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-cileungsi.html": "Harga Jayamix Cileungsi",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-cilegon.html": "Harga Jayamix Cilegon",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-ciputat.html": "Harga Jayamix Ciputat",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-cinere.html": "Harga Jayamix Cinere",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-indramayu.html": "Harga Jayamix Indramayu",
    "https://www.betonjayareadymix.com/2021/03/harga-jayamix-depok.html": "Harga Jayamix Depok",
    "https://www.betonjayareadymix.com/2018/05/harga-beton-ready-mix-surabaya.html": "Harga Beton Ready Mix Surabaya",
    "https://www.betonjayareadymix.com/2021/08/harga-beton-ready-mix-k350.html": "Harga Beton Ready Mix K350",
    "https://www.betonjayareadymix.com/2021/08/harga-beton-ready-mix-kediri.html": "Harga Beton Ready Mix Kediri",
    "https://www.betonjayareadymix.com/2021/08/harga-beton-ready-mix-semarang.html": "Harga Beton Ready Mix Semarang",
    "https://www.betonjayareadymix.com/2021/08/harga-beton-ready-mix-jogja.html": "Harga Beton Ready Mix Jogja",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-pionir.html": "Harga Beton Ready Mix Pionir",
    "https://www.betonjayareadymix.com/2018/05/harga-beton-ready-mix-adhimix.html": "Harga Beton Ready Mix Adhimix",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-holcim.html": "Harga Beton Ready Mix Holcim",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-jayamix.html": "Harga Beton Ready Mix Jayamix",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-merah-putih.html": "Harga Beton Ready Mix Merah Putih",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-b0.html": "Harga Beton Ready Mix B0",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-per-m3.html": "Harga Beton Ready Mix Per m3",
    "https://www.betonjayareadymix.com/2021/03/cari-harga-beton-ready-mix.html": "Cari Harga Beton Ready Mix",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-bandung.html": "Harga Beton Ready Mix Bandung",
    "https://www.betonjayareadymix.com/2021/03/harga-beton-ready-mix-bogor.html": "Harga Beton Ready Mix Bogor",
     "https://www.betonjayareadymix.com/2021/03/analisa-beton-ready-mix-k250.html": "Analisa Beton Ready Mix K250",
  "https://www.betonjayareadymix.com/2021/03/analisa-beton-ready-mix-k350.html": "Analisa Beton Ready Mix K350",
  "https://www.betonjayareadymix.com/2021/03/fungsi-beton-ready-mix.html": "Fungsi Beton Ready Mix",
  "https://www.betonjayareadymix.com/2021/03/jenis-beton-ready-mix.html": "Jenis Beton Ready Mix",
  "https://www.betonjayareadymix.com/2021/03/jual-beton-ready-mix.html": "Jual Beton Ready Mix",
  "https://www.betonjayareadymix.com/2021/03/beton-ready-mix-terdekat.html": "Beton Ready Mix Terdekat",
  "https://www.betonjayareadymix.com/2021/04/harga-ready-mix-holcim.html": "Harga Ready Mix Holcim",
  "https://www.betonjayareadymix.com/2021/04/harga-ready-mix-gresik.html": "Harga Ready Mix Gresik",
  "https://www.betonjayareadymix.com/2021/04/harga-ready-mix-cikarang.html": "Harga Ready Mix Cikarang",
  "https://www.betonjayareadymix.com/2021/04/harga-ready-mix-depok.html": "Harga Ready Mix Depok",
  "https://www.betonjayareadymix.com/2021/04/harga-ready-mix-bogor.html": "Harga Ready Mix Bogor",
"https://www.betonjayareadymix.com/2021/03/harga-ready-mix-cibinong.html": "Harga Ready Mix Cibinong",
  "https://www.betonjayareadymix.com/2018/04/cara-menghitung-kubikasi-beton.html": "Cara menghitung kubikasi beton",
  "https://www.betonjayareadymix.com/2018/04/analisa-beton-k-225.html": "Analisa Beton K 225",
  "https://www.betonjayareadymix.com/2021/08/cor-beton-murah.html": "Cor Beton Murah",
  "https://www.betonjayareadymix.com/2021/08/ready-mix-cor-bandung.html": "Ready Mix Cor Bandung",
  "https://www.betonjayareadymix.com/2021/08/beton-cor-merah-putih.html": "Beton Cor Merah Putih",
  "https://www.betonjayareadymix.com/2021/08/pionir-beton-cor-bogor.html": "Pionir Beton Cor Bogor",
  "https://www.betonjayareadymix.com/2021/08/batching-plant-terdekat.html": "Batching Plant Terdekat",
  "https://www.betonjayareadymix.com/2021/08/cor-beton-terdekat.html": "Cor Beton Terdekat",
  "https://www.betonjayareadymix.com/2021/08/cor-beton-bekasi.html": "Cor Beton Bekasi",
  "https://www.betonjayareadymix.com/2021/08/cor-beton-bandung.html": "Cor Beton Bandung",
  "https://www.betonjayareadymix.com/2018/04/1-truk-molen-berapa-m3.html": "1 Truk molen berapa m3",
  "https://www.betonjayareadymix.com/2018/04/macam-macam-mutu-beton.html": "Macam macam mutu beton",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-ready-mix-bandung.html": "Harga Cor Beton Ready Mix Bandung",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-di-jakarta.html": "Harga Cor Beton di Jakarta",
  "https://www.betonjayareadymix.com/2021/12/daftar-harga-cor-beton-jayamix.html": "Daftar Harga Cor Beton Jayamix",
  "https://www.betonjayareadymix.com/2021/12/daftar-harga-cor-beton.html": "Daftar Harga Cor Beton",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-k-300-per-m3.html": "Harga Cor Beton K 300 per m3",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-k-200.html": "Harga Cor Beton K 200",
  "https://www.betonjayareadymix.com/2018/05/harga-cor-beton-bertulang-per-m3.html": "Harga Cor Beton Bertulang per m3",
  "https://www.betonjayareadymix.com/2018/05/harga-cor-beton-bertulang.html": "Harga Cor Beton Bertulang",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-k-175.html": "Harga Cor Beton K 175",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-per-kubik.html": "Harga Cor Beton per kubik",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-k-275.html": "Harga Cor Beton K 275",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-minimix.html": "Harga Cor Beton Minimix",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-jayamix-per-kubik.html": "Harga Cor Beton Jayamix per kubik",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-sloof.html": "Harga Cor Beton Sloof",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-lantai.html": "Harga Cor Beton Lantai",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-jayamix.html": "Harga Cor Beton Jayamix",
  "https://www.betonjayareadymix.com/2021/12/harga-cor-beton-rumah-tinggal-per-m3.html": "Harga Cor Beton Rumah Tinggal per m3",
    "https://www.betonjayareadymix.com/2018/08/harga-jayamix-jayakerta.html": "Harga Jayamix Jayakerta",
    "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-jayakerta.html": "Harga Ready Mix Jayakerta",
    "https://www.betonjayareadymix.com/2018/08/harga-jayamix-kutawaluya.html": "Harga Jayamix Kutawaluya",
    "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-kutawaluya.html": "Harga Ready Mix Kutawaluya",
    "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-lemahabang-kab-karawang.html": "Harga Ready Mix Lemahabang Kab Karawang",
    "https://www.betonjayareadymix.com/2018/08/harga-jayamix-lemahabang-kab-karawang.html": "Harga Jayamix Lemahabang Kab Karawang",
    "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-majalaya-kab-karawang.html": "Harga Ready Mix Majalaya Kab Karawang",
    "https://www.betonjayareadymix.com/2018/08/harga-jayamix-majalaya-kab-karawang.html": "Harga Jayamix Majalaya Kab Karawang",
    "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-pakisjaya-kab-karawang.html": "Harga Ready Mix Pakisjaya Kab Karawang",
    "https://www.betonjayareadymix.com/2018/08/harga-jayamix-pakisjaya-kab-karawang.html": "Harga Jayamix Pakisjaya Kab Karawang",
     "https://www.betonjayareadymix.com/2018/08/harga-jayamix-tirtajaya-kab-karawang.html": "Harga Jayamix Tirtajaya Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-jayamix-banyusari-kab-karawang.html": "Harga Jayamix Banyusari Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-banyusari-kab-karawang.html": "Harga Ready Mix Banyusari Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-jayamix-batujaya-kab-karawang.html": "Harga Jayamix Batujaya Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-batujaya-kab-karawang.html": "Harga Ready Mix Batujaya Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-jayamix-ciampel-kab-karawang.html": "Harga Jayamix Ciampel Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-ciampel-kab-karawang.html": "Harga Ready Mix Ciampel Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-jayamix-cilamaya-kulon.html": "Harga Jayamix Cimalaya Kulon",
  "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-cilamaya-kulon.html": "Harga Ready Mix Cimalaya Kulon",
  "https://www.betonjayareadymix.com/2018/08/harga-jayamix-cikampek-karawang.html": "Harga Jayamix Cikampek Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-cikampek-karawang.html": "Harga Ready Mix Cikampek Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-jayamix-cibuaya-kab-karawang.html": "Harga Jayamix Cibuaya Kab Karawang",
  "https://www.betonjayareadymix.com/2018/08/harga-ready-mix-cibuaya-kab-karawang.html": "Harga Ready Mix Cibuaya Kab Karawang",
"https://www.betonjayareadymix.com/2018/07/harga-ready-mix-cikeusal-kab-serang.html": "Harga Ready Mix Cikeusal Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-cikeusal-kab-serang.html": "Harga Jayamix Cikeusal Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-cinangka-kab-serang.html": "Harga Ready Mix Cinangka Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-cinangka-kab-serang.html": "Harga Jayamix Cinangka Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-ciomas-kab-serang.html": "Harga Ready Mix Ciomas Kab Serang",
         "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-mancak-kab-serang.html": "Harga Ready Mix Mancak Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-mancak-kab-serang.html": "Harga Jayamix Mancak Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-pabuaran-kab-serang.html": "Harga Ready Mix Pabuaran Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-pabuaran-kab-serang.html": "Harga Jayamix Pabuaran Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-padarincang-kab-serang.html": "Harga Ready Mix Padarincang Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-padarincang-kab-serang.html": "Harga Jayamix Padarincang Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-pamarayan-kab-serang.html": "Harga Ready Mix Pamarayan Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-pamarayan-kab-serang.html": "Harga Jayamix Pamarayan Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-petir-kab-serang.html": "Harga Ready Mix Petir Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-petir-kab-serang.html": "Harga Jayamix Petir Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-pontang-kab-serang.html": "Harga Ready Mix Pontang Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-pontang-kab-serang.html": "Harga Jayamix Pontang Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-pulo-kab-serang.html": "Harga Ready Mix Pulo Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-pulo-kab-serang.html": "Harga Jayamix Pulo Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tanara-kab-serang.html": "Harga Ready Mix Tanara Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tanara-kab-serang.html": "Harga Jayamix Tanara Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-waringinkurung.html": "Harga Ready Mix Waringinkurung Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-waringinkurung-kab-serang.html": "Harga Jayamix Waringinkurung Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tunjung-kab-serang.html": "Harga Ready Mix Tunjung Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tunjung-kab-serang.html": "Harga Jayamix Tunjung Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tirtayasa-kab-serang.html": "Harga Ready Mix Tirtayasa Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tirtayasa-kab-serang.html": "Harga Jayamix Tirtayasa Kab Serang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sindang-jaya.html": "Harga Jayamix Sindang Jaya",
  
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sindang-jaya-kab-tangerang.html": "Harga Ready Mix Sindang Jaya Kab. Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-cikupa-kab-tangerang.html": "Harga Jayamix Cikupa Kab. Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-cikupa.html": "Harga Ready Mix Cikupa",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-balaraja-kab-tangerang.html": "Harga Ready Mix Balaraja Kab. Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-balaraja-kab-tangerang.html": "Harga Jayamix Balaraja Kab. Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-gunung-kaler-kab-tangerang.html": "Harga Ready Mix Gunung Kaler Kab. Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-gunung-kaler-kab-tangerang.html": "Harga Jayamix Gunung Kaler Kab. Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-jayanti-kab-tangerang.html": "Harga Jayamix Jayanti Kab. Tangerang",
     "https://www.betonjayareadymix.com/harga-ready-mix-jayanti": "Harga Ready Mix Jayanti - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-kosambi": "Harga Jayamix Kosambi - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-kosambi": "Harga Ready Mix Kosambi - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-kronjo": "Harga Ready Mix Kronjo - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-kronjo": "Harga Jayamix Kronjo - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-kresek": "Harga Jayamix Kresek - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-kresek": "Harga Ready Mix Kresek - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-kemiri": "Harga Jayamix Kemiri - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-kemiri": "Harga Ready Mix Kemiri - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-kelapa-dua": "Harga Ready Mix Kelapa Dua - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-kelapa-dua": "Harga Jayamix Kelapa Dua - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-mauk": "Harga Jayamix Mauk - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-mauk": "Harga Ready Mix Mauk - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-legok": "Harga Ready Mix Legok - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-legok": "Harga Jayamix Legok - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-mekarbaru": "Harga Ready Mix Mekarbaru - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-mekarbaru": "Harga Jayamix Mekarbaru - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-pasar-kemis": "Harga Ready Mix Pasar Kemis - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-pasar-kemis": "Harga Jayamix Pasar Kemis - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-jayamix-panongan": "Harga Jayamix Panongan - Kab. Tangerang",
    "https://www.betonjayareadymix.com/harga-ready-mix-panongan": "Harga Ready Mix Panongan - Kab. Tangerang",
        "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sukamulya.html": "Harga Jayamix Sukamulya",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sukamulya.html": "Harga Ready Mix Sukamulya",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sukadiri.html": "Harga Ready Mix Sukadiri",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sukadiri.html": "Harga Jayamix Sukadiri",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-solear.html": "Harga Jayamix Solear",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-solear.html": "Harga Ready Mix Solear",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sepatan-timur.html": "Harga Ready Mix Sepatan Timur",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sepatan-timur.html": "Harga Jayamix Sepatan Timur",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sepatan.html": "Harga Ready Mix Sepatan",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sepatan.html": "Harga Jayamix Sepatan",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tigaraksa-kab-tangerang.html": "Harga Jayamix Tigaraksa Kab Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tigaraksa-kab-tangerang.html": "Harga Ready Mix Tigaraksa Kab Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-cisoka.html": "Harga Jayamix Cisoka",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-cisoka.html": "Harga Ready Mix Cisoka",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-batu-ceper.html": "Harga Ready Mix Batu Ceper",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-batu-ceper.html": "Harga Jayamix Batu Ceper",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-benda-kota-tangerang.html": "Harga Jayamix Benda Kota Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-benda-kota-tangerang.html": "Harga Ready Mix Benda Kota Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-cibodas-kota-tangerang.html": "Harga Ready Mix Cibodas Kota Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-cibodas-kota-tangerang.html": "Harga Jayamix Cibodas Kota Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-ciledug-kota-tangerang.html": "Harga Jayamix Ciledug Kota Tangerang",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-serpong.html": "Harga Ready Mix Serpong",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-serpong.html": "Harga Jayamix Serpong",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-serpong-utara.html": "Harga Ready Mix Serpong Utara",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-serpong-utara.html": "Harga Jayamix Serpong Utara",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-setu-tangerang-selatan.html": "Harga Jayamix Setu Tangerang Selatan",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-setu-tangerang-selatan.html": "Harga Ready Mix Setu Tangerang Selatan",

    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-ciomas-kab-bogor.html": "Harga Jayamix Ciomas Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-ciomas-kab-bogor.html": "Harga Ready Mix Ciomas Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-cisarua-kab-bogor.html": "Harga Jayamix Cisarua Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-cisarua-kab-bogor.html": "Harga Ready Mix Cisarua Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-ciseeng-kab-bogor.html": "Harga Jayamix Ciseeng Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-ciseeng-kab-bogor.html": "Harga Ready Mix Ciseeng Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tenjolaya-kab-bogor.html": "Harga Jayamix Tenjolaya Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tenjolaya-kab-bogor.html": "Harga Ready Mix Tenjolaya Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tenjo-kab-bogor.html": "Harga Jayamix Tenjo Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tenjo-kab-bogor.html": "Harga Ready Mix Tenjo Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tanjungsari-kab-bogor.html": "Harga Jayamix Tanjungsari Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tanjungsari-kab-bogor.html": "Harga Ready Mix Tanjungsari Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tamansari-kab-bogor.html": "Harga Jayamix Tamansari Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tamansari-kab-bogor.html": "Harga Ready Mix Tamansari Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-tajur-halang-kab-bogor.html": "Harga Jayamix Tajur Halang Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-tajur-halang-kab-bogor.html": "Harga Ready Mix Tajur Halang Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sukaraja-kab-bogor.html": "Harga Jayamix Sukaraja Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sukaraja-kab-bogor.html": "Harga Ready Mix Sukaraja Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sukamakmur-kab-bogor.html": "Harga Ready Mix Sukamakmur Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sukamakmur-kab-bogor.html": "Harga Jayamix Sukamakmur Kab Bogor",
     "https://www.betonjayareadymix.com/2018/07/harga-jayamix-parung-panjang-kab-bogor.html": "Harga Jayamix Parung Panjang Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-parung-kab-bogor.html": "Harga Ready Mix Parung Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-pamijahan-kab-bogor.html": "Harga Jayamix Pamijahan Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-pamijahan-kab-bogor.html": "Harga Ready Mix Pamijahan Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-nanggung-kab-bogor.html": "Harga Jayamix Nanggung Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-nanggung-kab-bogor.html": "Harga Ready Mix Nanggung Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-megamendung-kab-bogor.html": "Harga Jayamix Megamendung Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-megamendung-kab-bogor.html": "Harga Ready Mix Megamendung Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-leuwisadeng-kab-bogor.html": "Harga Jayamix Leuwisadeng Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-leuwisadeng-kab-bogor.html": "Harga Ready Mix Leuwisadeng Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-leuwiliang-kab-bogor.html": "Harga Jayamix Leuwiliang Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-leuwiliang-kab-bogor.html": "Harga Ready Mix Leuwiliang Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-klapanunggal-kab-bogor.html": "Harga Jayamix Klapanunggal Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-klapanunggal-kab-bogor.html": "Harga Ready Mix Klapanunggal Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-kemang-kab-bogor.html": "Harga Jayamix Kemang Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-kemang-kab-bogor.html": "Harga Ready Mix Kemang Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-jonggol-kab-bogor.html": "Harga Jayamix Jonggol Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-jonggol-kab-bogor.html": "Harga Ready Mix Jonggol Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-jayamix-jasinga-kab-bogor.html": "Harga Jayamix Jasinga Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-jasinga-kab-bogor.html": "Harga Ready Mix Jasinga Kab Bogor",
  "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-sukajaya-kab-bogor.html": "Harga Ready Mix Sukajaya Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-jayamix-sukajaya-kab-bogor.html": "Harga Jayamix Sukajaya Kab Bogor",
    "https://www.betonjayareadymix.com/2018/07/harga-ready-mix-rumpin-kab-bogor.html": "Harga Ready Mix Rumpin Kab Bogor",
    
      
    "https://www.betonjayareadymix.com/2021/08/harga-cor-beton-dinding.html": "Harga Cor Beton Dinding",
    "https://www.betonjayareadymix.com/2021/03/harga-borongan-cor-beton.html": "Harga Borongan Cor Beton",
    "https://www.betonjayareadymix.com/2021/03/harga-borongan-cor-beton-per-m3.html": "Harga Borongan Cor Beton per m3",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-townhouse.html": "Borongan Cor Beton Townhouse",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-villa.html": "Borongan Cor Beton Villa",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-pabrik.html": "Borongan Cor Beton Pabrik",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-gedung.html": "Borongan Cor Beton Gedung",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-gudang.html": "Borongan Cor Beton Gudang",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-masjid.html": "Borongan Cor Beton Masjid",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-yayasan.html": "Borongan Cor Beton Yayasan",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-mall.html": "Borongan Cor Beton Mall",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-stadion.html": "Borongan Cor Beton Stadion",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-stasiun.html": "Borongan Cor Beton Stasiun",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-sekolah.html": "Borongan Cor Beton Sekolah",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-pelabuhan.html": "Borongan Cor Beton Pelabuhan",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-bandara.html": "Borongan Cor Beton Bandara",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-jalan-desa.html": "Borongan Cor Beton Jalan Desa",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-jalan-raya.html": "Borongan Cor Beton Jalan Raya",
  "https://www.betonjayareadymix.com/2018/09/borongan-cor-beton-jalan-tol.html": "Borongan Cor Beton Jalan Tol",
  "https://www.betonjayareadymix.com/2018/09/cor-beton-bangunan.html": "Cor Beton Bangunan",
  "https://www.betonjayareadymix.com/2018/08/office-kantor-scg-kalibata.html": "Office Kantor Scg Kalibata",
  "https://www.betonjayareadymix.com/2018/08/scg-batching-plant.html": "Scg Batching Plant",
  "https://www.betonjayareadymix.com/2018/04/scg-readymix.html": "Scg Ready Mix",
  "https://www.betonjayareadymix.com/2018/04/scg-jayamix.html": "Scg Jayamix",
  "https://www.betonjayareadymix.com/2018/08/scg-beton.html": "Scg Beton",
  "https://www.betonjayareadymix.com/2021/03/pt-scg-readymix-indonesia.html": "PT Scg Ready Mix Indonesia",
  "https://www.betonjayareadymix.com/2021/03/scg-readymix-indonesia.html": "Scg Ready Mix Indonesia",
  "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-subang.html": "Batching Plant Scg Subang",
  "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-karawang.html": "Batching Plant Scg Karawang",
  "https://www.betonjayareadymix.com/2018/08/batching-plant-sukabumi.html": "Batching Plant Sukabumi",
  "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-purwakarta.html": "Batching Plant Scg Purwakarta",
  "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-majalengka.html": "Batching Plant Scg Majalengka",
  "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-bandung.html": "Batching Plant Scg Bandung",
  "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-cirebon.html": "Batching plant Scg Cirebon",
        "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-cianjur.html": "Batching plant Scg Cianjur",
        "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-bogor.html": "Batching plant Scg Bogor",
        "https://www.betonjayareadymix.com/2018/08/batching-plant-scg-bekasi.html": "Batching plant Scg Bekasi",
        "https://www.betonjayareadymix.com/2018/08/scg-jakarta.html": "Scg Jakarta",
        "https://www.betonjayareadymix.com/2018/08/scg-jayamix-dki-jakarta.html": "Scg Jayamix DKI Jakarta",
        "https://www.betonjayareadymix.com/2018/04/scg-readymix-jakarta.html": "Scg Ready Mix Jakarta",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-kota-jakarta-utara.html": "Scg Ready Mix Kota Jakarta Utara",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-kota-jakarta-selatan.html": "Scg Ready Mix Jakarta Selatan",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-kota-jakarta-barat.html": "Scg Ready Mix Kota Jakarta Barat",
        "https://www.betonjayareadymix.com/2018/08/plant-scg-jelambar.html": "Plant Scg Jelambar",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-kota-jakarta-timur.html": "Scg Ready Mix Kota Jakarta Timur",
        "https://www.betonjayareadymix.com/2018/08/plant-scg-kampung-rambutan.html": "Plant Scg Kampung Rambutan",
        "https://www.betonjayareadymix.com/2018/08/plant-scg-kebon-nanas-jakarta-timur.html": "Plant Scg Kebon Nanas Jakarta Timur",
        "https://www.betonjayareadymix.com/2018/08/scg-jayamix-depok.html": "Scg Jayamix Depok",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-depok.html": "Scg Ready Mix Depok",
        "https://www.betonjayareadymix.com/2018/08/scg-jayamix-bekasi.html": "Scg Jayamix Bekasi",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-bekasi.html": "Scg Ready Mix Bekasi",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-cikarang-selatan.html": "Scg Ready Mix Cikarang Selatan",
        "https://www.betonjayareadymix.com/2018/08/scg-jayamix-bogor.html": "Scg Jayamix Bogor",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-bogor.html": "Scg Ready Mix Bogor",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-babakan-madang-kab-bogor.html": "Scg Ready Mix Babakan Madang Kab Bogor",
        "https://www.betonjayareadymix.com/2018/08/scg-jayamix-tangerang.html": "Scg Jayamix Tangerang",
        "https://www.betonjayareadymix.com/2018/08/scg-ready-mix-tangerang.html": "Scg Ready Mix Tangerang"
};
document.addEventListener("DOMContentLoaded", function() {
    // var currentUrl = window.location.href;
     //const cleanUrl = currentUrl.split('?')[0]; // Menghapus parameter seperti ?m=1
    const cleanUrl = window.location.href.split(/[?#]/)[0]; // Menghilangkan parameter seperti ?m=1

     // Menemukan elemen menggunakan ID
      var materialKonstruksiLink = document.getElementById("materialKonstruksi");
     var readyMixLink = document.getElementById("readyMix");
     var pageNameSpan = document.getElementById("pageNameSpan");

     // Default untuk menyembunyikan elemen
     materialKonstruksiLink.style.visibility = 'hidden';
     readyMixLink.style.visibility = 'hidden';
     pageNameSpan.textContent = "";
  
    console.log('Material Konstruksi:', materialKonstruksiLink);
    console.log('Ready Mix:', readyMixLink);
    console.log('Page Name Span:', pageNameSpan);

    if (!materialKonstruksiLink || !readyMixLink || !pageNameSpan) {
        console.error("Salah satu elemen tidak ditemukan!");
        return;
    }

    if (urlMapping[cleanUrl]) {
        materialKonstruksiLink.style.visibility = 'visible';
        readyMixLink.style.visibility = 'visible';
        pageNameSpan.textContent = urlMapping[cleanUrl];
    }
   });
